version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  MAVEN_VERSION: 3.6.3
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk11
install:
  # Prepend Java entry, remove Ruby entry (C:\Ruby193\bin;) from PATH
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%;
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean install
cache:
  - C:\Users\appveyor\.m2\ -> pom.xml

artifacts:
  - path: C:\Users\appveyor\.m2\
    name: Build Snapshot
    type: zip